# docker-compose.yml

# 指定 docker-compose 文件版本
version: '3.8'

# 定义所有服务
services:
  # 后端服务
  backend:
    # 构建指令：使用 backend 文件夹下的 Dockerfile 来构建镜像
    build: ./backend
    # 给容器起个名字，方便管理
    container_name: homepage-backend
    # 设置重启策略：无论何种情况退出，都自动重启
    restart: always
    # 数据卷挂载 (非常重要！)
    # 将主机(服务器)的 ./backend/data 目录映射到容器的 /app/data 目录
    # 这样数据库文件就会保存在服务器上，即使容器被删除，数据也不会丢失
    volumes:
      - ${PWD}/backend/data:/app/data
      - ${PWD}/backend/logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/backend/judge_tmp:/app/judge_tmp

  # 前端服务
  frontend:
    build: ./frontend
    container_name: homepage-frontend
    restart: always
    # 端口映射 (非常重要！)
    # 将主机(服务器)的 80 端口映射到容器的 80 端口
    # 这样用户通过公网 IP 访问时，请求就会进入前端 Nginx 容器
    ports:
      - "80:80"
    # 设置依赖关系
    # 确保 backend 服务启动之后，再启动 frontend 服务
    depends_on:
      - backend